{
 "title": "weather_dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "humidity_difference",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_timestamp,1h,previous),\n  city_name AS metric,\n  avg(humidity_difference) AS \"humidity_difference\"\nFROM weather_data\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:300%;font-weight:Bold ;color:#CD5C5C;\">Weather Data</p>"
   }
  },
  {
   "title": "windspeed_difference",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_timestamp,1h),\n  city_name AS metric,\n  avg(wind_speed_difference) AS \"wind_speed_difference\"\nFROM weather_data\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_timestamp,1h),\n  city_name AS metric,\n  avg(avg_temperature_in_window) AS \"avg_temperature_in_window\"\nFROM weather_data\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_timestamp AS \"time\",\n  city_name AS metric,\n  humidity\nFROM weather_data\nWHERE\n  $__timeFilter(start_timestamp)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "min_temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_timestamp AS \"time\",\n  city_name AS metric,\n  min_temperature_in_window\nFROM weather_data\nWHERE\n  $__timeFilter(start_timestamp)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Max_temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_timestamp AS \"time\",\n  city_name AS metric,\n  max_temperature_in_window\nFROM weather_data\n"
    }
   ]
  },
  {
   "title": "Wind_speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_timestamp AS \"time\",\n  city_name AS metric,\n  wind_speed\nFROM weather_data\nORDER BY 1,2"
    }
   ]
  }
 ]
}